#include <iostream>

//extern "C" coompiler directive, supresses name mangling, can be applied
// to only one function in a set of overloaded functions
// Allows c++ funtions to be called from c or other languages

//two or more functions can have same name, arguments have to be diffrent
//resolved at compile time, called static polymorphisim

// Name mangling 
//-unique name generated by compiler for functions
//-allows linker to link the call with correct overloaded function
int Add(int a, int b) {
    return a + b;
}

double Add(double a, double b) {
    return a + b;
}

//default parameters if only some or no arguments are provided
int default(int a = 3, int b = 3) {
    return a + b;
}

int main() {
    int result = Add(3, 5);
    double res = Add(3.1, 4.2);
}